import type {
  User,
  Task,
  Message,
  Note,
  CalendarEvent,
  ChatContact,
} from "./types";

export const users: User[] = [
  {
    id: "u1",
    name: "Andi Pratama",
    email: "andi@owtask.com",
    role: "leader",
    division: "Engineering",
    avatar: "",
    phone: "081234567890",
    joinDate: "2024-01-15",
    companyId: "c1",
  },
  {
    id: "u2",
    name: "Sari Dewi",
    email: "sari@owtask.com",
    role: "leader",
    division: "Marketing",
    avatar: "",
    phone: "081234567891",
    joinDate: "2024-02-01",
    companyId: "c1",
  },
  {
    id: "u3",
    name: "Budi Santoso",
    email: "budi@owtask.com",
    role: "worker",
    division: "Engineering",
    avatar: "",
    phone: "081234567892",
    joinDate: "2024-03-10",
    companyId: "c1",
  },
  {
    id: "u4",
    name: "Maya Putri",
    email: "maya@owtask.com",
    role: "worker",
    division: "Engineering",
    avatar: "",
    phone: "081234567893",
    joinDate: "2024-03-15",
    companyId: "c1",
  },
  {
    id: "u5",
    name: "Rizky Firmansyah",
    email: "rizky@owtask.com",
    role: "worker",
    division: "Marketing",
    avatar: "",
    phone: "081234567894",
    joinDate: "2024-04-01",
    companyId: "c1",
  },
  {
    id: "u6",
    name: "Diana Putri",
    email: "diana@owtask.com",
    role: "worker",
    division: "Marketing",
    avatar: "",
    phone: "081234567895",
    joinDate: "2024-04-10",
    companyId: "c1",
  },
  {
    id: "u7",
    name: "Farhan Maulana",
    email: "farhan@owtask.com",
    role: "worker",
    division: "Design",
    avatar: "",
    phone: "081234567896",
    joinDate: "2024-05-01",
    companyId: "c1",
  },
  {
    id: "u8",
    name: "Lestari Wulan",
    email: "lestari@owtask.com",
    role: "worker",
    division: "Design",
    avatar: "",
    phone: "081234567897",
    joinDate: "2024-05-15",
    companyId: "c1",
  },
  {
    id: "u9",
    name: "Rina Amelia",
    email: "rina@owtask.com",
    role: "worker",
    division: "",
    avatar: "",
    phone: "",
    joinDate: "2026-06-27",
    isNew: true,
  },
];

export const currentUser = users[0];

export const tasks: Task[] = [
  {
    id: "t1",
    title: "Desain UI Dashboard v2",
    description:
      "Buat desain ulang dashboard dengan tema baru yang lebih modern. Gunakan gradient biru dan efek translucent.",
    type: "group",
    status: "in_progress",
    priority: "high",
    assigneeIds: ["u3", "u4", "u7"],
    leaderId: "u1",
    deadline: "2026-07-15",
    createdAt: "2026-06-20",
    attachments: [],
    submissions: [],
    division: "Engineering",
  },
  {
    id: "t2",
    title: "Implementasi API Authentication",
    description:
      "Buat endpoint REST API untuk login, register, dan logout. Gunakan JWT token.",
    type: "individual",
    status: "pending",
    priority: "high",
    assigneeIds: ["u3"],
    leaderId: "u1",
    deadline: "2026-07-10",
    createdAt: "2026-06-22",
    attachments: [],
    submissions: [],
    division: "Engineering",
  },
  {
    id: "t3",
    title: "Konten Instagram Bulanan",
    description:
      "Buat 12 konten Instagram untuk bulan Juli. Tema: produktivitas tim kerja.",
    type: "group",
    status: "in_progress",
    priority: "medium",
    assigneeIds: ["u5", "u6"],
    leaderId: "u2",
    deadline: "2026-07-01",
    createdAt: "2026-06-18",
    attachments: [],
    submissions: [],
    division: "Marketing",
  },
  {
    id: "t4",
    title: "Landing Page Company Profile",
    description:
      "Buat landing page baru untuk company profile. Responsive dan SEO friendly.",
    type: "individual",
    status: "completed",
    priority: "medium",
    assigneeIds: ["u7"],
    leaderId: "u1",
    deadline: "2026-06-30",
    createdAt: "2026-06-10",
    attachments: [],
    submissions: [
      {
        id: "s1",
        taskId: "t4",
        workerId: "u7",
        content: "Landing page sudah selesai. Silakan review.",
        attachments: [],
        submittedAt: "2026-06-28",
        status: "approved",
      },
    ],
    division: "Design",
  },
  {
    id: "t5",
    title: "Video Tutorial Produk",
    description: "Buat video tutorial penggunaan produk berdurasi 5 menit.",
    type: "individual",
    status: "overdue",
    priority: "high",
    assigneeIds: ["u5"],
    leaderId: "u2",
    deadline: "2026-06-25",
    createdAt: "2026-06-15",
    attachments: [],
    submissions: [],
    division: "Marketing",
  },
  {
    id: "t6",
    title: "Testing Aplikasi Mobile",
    description:
      "Lakukan testing end-to-end untuk aplikasi mobile versi terbaru.",
    type: "group",
    status: "pending",
    priority: "medium",
    assigneeIds: ["u3", "u4"],
    leaderId: "u1",
    deadline: "2026-07-20",
    createdAt: "2026-06-25",
    attachments: [],
    submissions: [],
    division: "Engineering",
  },
  {
    id: "t7",
    title: "Desain Banner Promosi",
    description: "Buat 5 banner promosi untuk campaign Lebaran.",
    type: "group",
    status: "in_progress",
    priority: "low",
    assigneeIds: ["u7", "u8"],
    leaderId: "u1",
    deadline: "2026-07-25",
    createdAt: "2026-06-24",
    attachments: [],
    submissions: [],
    division: "Design",
  },
  {
    id: "t8",
    title: "Optimasi Database",
    description:
      "Optimasi query database untuk meningkatkan performa aplikasi.",
    type: "individual",
    status: "pending",
    priority: "high",
    assigneeIds: ["u4"],
    leaderId: "u1",
    deadline: "2026-07-05",
    createdAt: "2026-06-23",
    attachments: [],
    submissions: [],
    division: "Engineering",
  },
  {
    id: "t9",
    title: "Riset Kompetitor",
    description:
      "Analisis 5 kompetitor utama: fitur, pricing, kelebihan dan kekurangan.",
    type: "group",
    status: "in_progress",
    priority: "medium",
    assigneeIds: ["u5", "u6"],
    leaderId: "u2",
    deadline: "2026-07-08",
    createdAt: "2026-06-20",
    attachments: [],
    submissions: [],
    division: "Marketing",
  },
  {
    id: "t10",
    title: "Integrasi Payment Gateway",
    description:
      "Integrasikan Midtrans untuk pembayaran online. Support kartu kredit, VA, dan e-wallet.",
    type: "individual",
    status: "pending",
    priority: "high",
    assigneeIds: ["u3"],
    leaderId: "u1",
    deadline: "2026-07-12",
    createdAt: "2026-06-22",
    attachments: [],
    submissions: [],
    division: "Engineering",
  },
  {
    id: "t11",
    title: "Desain UI Mobile App",
    description:
      "Buat wireframe dan high-fidelity design untuk aplikasi mobile iOS & Android.",
    type: "group",
    status: "in_progress",
    priority: "high",
    assigneeIds: ["u7", "u8"],
    leaderId: "u1",
    deadline: "2026-07-18",
    createdAt: "2026-06-19",
    attachments: [],
    submissions: [],
    division: "Design",
  },
  {
    id: "t12",
    title: "Copywriting Landing Page",
    description: "Tulis copy untuk halaman utama, fitur, pricing, dan FAQ.",
    type: "individual",
    status: "completed",
    priority: "medium",
    assigneeIds: ["u6"],
    leaderId: "u2",
    deadline: "2026-06-28",
    createdAt: "2026-06-15",
    attachments: [],
    submissions: [
      {
        id: "s2",
        taskId: "t12",
        workerId: "u6",
        content: "Copy sudah selesai untuk semua halaman.",
        attachments: [],
        submittedAt: "2026-06-27",
        status: "approved",
      },
    ],
    division: "Marketing",
  },
  {
    id: "t13",
    title: "Setup CI/CD Pipeline",
    description:
      "Konfigurasi GitHub Actions untuk automated testing dan deployment ke Vercel.",
    type: "individual",
    status: "completed",
    priority: "high",
    assigneeIds: ["u4"],
    leaderId: "u1",
    deadline: "2026-06-26",
    createdAt: "2026-06-18",
    attachments: [],
    submissions: [
      {
        id: "s3",
        taskId: "t13",
        workerId: "u4",
        content: "Pipeline sudah working. Auto deploy ke staging.",
        attachments: [],
        submittedAt: "2026-06-25",
        status: "approved",
      },
    ],
    division: "Engineering",
  },
  {
    id: "t14",
    title: "Video Promosi TikTok",
    description:
      "Buat 3 video promosi untuk TikTok. Durasi 30-60 detik, style modern.",
    type: "group",
    status: "pending",
    priority: "medium",
    assigneeIds: ["u5", "u6"],
    leaderId: "u2",
    deadline: "2026-07-15",
    createdAt: "2026-06-24",
    attachments: [],
    submissions: [],
    division: "Marketing",
  },
  {
    id: "t15",
    title: "Implementasi Dark Mode",
    description:
      "Tambahkan fitur dark mode ke seluruh aplikasi. Gunakan CSS variables dan toggle.",
    type: "individual",
    status: "in_progress",
    priority: "low",
    assigneeIds: ["u3"],
    leaderId: "u1",
    deadline: "2026-07-22",
    createdAt: "2026-06-21",
    attachments: [],
    submissions: [],
    division: "Engineering",
  },
  {
    id: "t16",
    title: "Logo Redesign",
    description:
      "Redesign logo owTask dengan konsep modern dan minimalis. File vector SVG.",
    type: "individual",
    status: "in_progress",
    priority: "medium",
    assigneeIds: ["u7"],
    leaderId: "u1",
    deadline: "2026-07-03",
    createdAt: "2026-06-20",
    attachments: [],
    submissions: [],
    division: "Design",
  },
  {
    id: "t17",
    title: "Email Marketing Campaign",
    description:
      "Buat sequence email untuk onboarding user baru. 5 email dalam 2 minggu.",
    type: "individual",
    status: "pending",
    priority: "low",
    assigneeIds: ["u6"],
    leaderId: "u2",
    deadline: "2026-07-25",
    createdAt: "2026-06-25",
    attachments: [],
    submissions: [],
    division: "Marketing",
  },
  {
    id: "t18",
    title: "API Documentation",
    description:
      "Dokumentasikan semua endpoint REST API menggunakan OpenAPI/Swagger.",
    type: "individual",
    status: "pending",
    priority: "medium",
    assigneeIds: ["u4"],
    leaderId: "u1",
    deadline: "2026-07-28",
    createdAt: "2026-06-24",
    attachments: [],
    submissions: [],
    division: "Engineering",
  },
  {
    id: "t19",
    title: "Prototype Fitur Chat",
    description:
      "Buat prototype fitur chat real-time menggunakan WebSocket. Termasuk typing indicator.",
    type: "group",
    status: "overdue",
    priority: "high",
    assigneeIds: ["u3", "u4"],
    leaderId: "u1",
    deadline: "2026-06-20",
    createdAt: "2026-06-10",
    attachments: [],
    submissions: [],
    division: "Engineering",
  },
  {
    id: "t20",
    title: "Content Calendar Q3",
    description:
      "Rencanakan konten social media untuk Q3 2026. Termasuk caption, visual, dan jadwal.",
    type: "group",
    status: "completed",
    priority: "medium",
    assigneeIds: ["u5", "u6"],
    leaderId: "u2",
    deadline: "2026-06-30",
    createdAt: "2026-06-12",
    attachments: [],
    submissions: [
      {
        id: "s4",
        taskId: "t20",
        workerId: "u5",
        content: "Content calendar Q3 sudah jadi. 90 konten terencana.",
        attachments: [],
        submittedAt: "2026-06-29",
        status: "approved",
      },
    ],
    division: "Marketing",
  },
  {
    id: "t21",
    title: "Design System Dokumentasi",
    description:
      "Buat dokumentasi design system: color palette, typography, spacing, komponen.",
    type: "individual",
    status: "in_progress",
    priority: "medium",
    assigneeIds: ["u8"],
    leaderId: "u1",
    deadline: "2026-07-10",
    createdAt: "2026-06-22",
    attachments: [],
    submissions: [],
    division: "Design",
  },
  {
    id: "t22",
    title: "Setup Monitoring & Alerting",
    description:
      "Konfigurasi Grafana + Prometheus untuk monitoring server. Setup alert ke Slack.",
    type: "individual",
    status: "pending",
    priority: "high",
    assigneeIds: ["u4"],
    leaderId: "u1",
    deadline: "2026-07-08",
    createdAt: "2026-06-25",
    attachments: [],
    submissions: [],
    division: "Engineering",
  },
  {
    id: "t23",
    title: "Photoshoot Produk",
    description:
      "Foto produk untuk katalog online. Lighting professional, background putih.",
    type: "group",
    status: "pending",
    priority: "low",
    assigneeIds: ["u7", "u8"],
    leaderId: "u2",
    deadline: "2026-07-30",
    createdAt: "2026-06-26",
    attachments: [],
    submissions: [],
    division: "Design",
  },
  {
    id: "t24",
    title: "Refactor Component Library",
    description:
      "Refactor semua komponen UI menggunakan Compound Component pattern. Improve TypeScript.",
    type: "group",
    status: "in_progress",
    priority: "medium",
    assigneeIds: ["u3", "u4"],
    leaderId: "u1",
    deadline: "2026-07-20",
    createdAt: "2026-06-20",
    attachments: [],
    submissions: [],
    division: "Engineering",
  },
];

export const messages: Message[] = [
  // Task chat for t1
  {
    id: "m1",
    senderId: "u1",
    content:
      "Halo tim, silakan mulai desain dashboard v2. gunakan referensi yang sudah saya kirim sebelumnya.",
    timestamp: "2026-06-20T09:00:00",
    type: "text",
    taskId: "t1",
  },
  {
    id: "m2",
    senderId: "u3",
    content: "Baik pak, saya mulai dari wireframe dulu.",
    timestamp: "2026-06-20T09:15:00",
    type: "text",
    taskId: "t1",
  },
  {
    id: "m3",
    senderId: "u7",
    content: "Saya bantu bikin color palette dan component library nya ya.",
    timestamp: "2026-06-20T09:20:00",
    type: "text",
    taskId: "t1",
  },
  {
    id: "m4",
    senderId: "u4",
    content: "Oke, saya fokus ke responsive layout.",
    timestamp: "2026-06-20T09:30:00",
    type: "text",
    taskId: "t1",
  },
  {
    id: "m5",
    senderId: "u1",
    content: "Bagus! Deadline 15 Juli ya. Update progress setiap hari.",
    timestamp: "2026-06-20T09:35:00",
    type: "text",
    taskId: "t1",
  },
  {
    id: "m6",
    senderId: "u3",
    content: "Wireframe sudah 80% nih, saya share ya.",
    timestamp: "2026-06-21T10:00:00",
    type: "text",
    taskId: "t1",
  },
  {
    id: "m7",
    senderId: "u7",
    content:
      "Color palette udah jadi. Aku pakai shades of green kayak referensi.",
    timestamp: "2026-06-21T14:00:00",
    type: "text",
    taskId: "t1",
  },

  // Task chat for t11
  {
    id: "m20",
    senderId: "u1",
    content:
      "Tim desain, tolong prioritasin mobile app design ya. Client request.",
    timestamp: "2026-06-22T08:00:00",
    type: "text",
    taskId: "t11",
  },
  {
    id: "m21",
    senderId: "u7",
    content: "Siap pak. Saya mulai dari user flow hari ini.",
    timestamp: "2026-06-22T08:30:00",
    type: "text",
    taskId: "t11",
  },
  {
    id: "m22",
    senderId: "u8",
    content: "Saya bantu wireframe untuk halaman profile ya.",
    timestamp: "2026-06-22T09:00:00",
    type: "text",
    taskId: "t11",
  },

  // Universal chat
  {
    id: "m10",
    senderId: "u2",
    content: "Halo semua! Meeting jam 3 sore ya.",
    timestamp: "2026-06-25T08:00:00",
    type: "text",
  },
  {
    id: "m11",
    senderId: "u1",
    content: "Oke, saya join.",
    timestamp: "2026-06-25T08:05:00",
    type: "text",
  },
  {
    id: "m12",
    senderId: "u5",
    content: "Siap pak!",
    timestamp: "2026-06-25T08:10:00",
    type: "text",
  },
  {
    id: "m13",
    senderId: "u3",
    content: "Saya juga join. Ada agenda apa aja?",
    timestamp: "2026-06-25T08:15:00",
    type: "text",
  },
  {
    id: "m14",
    senderId: "u2",
    content: "Bahasan sprint review dan planning bulan depan.",
    timestamp: "2026-06-25T08:20:00",
    type: "text",
  },
  {
    id: "m15",
    senderId: "u7",
    content: "Progress desain mobile app udah 60% nih.",
    timestamp: "2026-06-25T10:00:00",
    type: "text",
  },
  {
    id: "m16",
    senderId: "u4",
    content: "CI/CD pipeline udah ready. Auto deploy ke staging jalan.",
    timestamp: "2026-06-25T11:00:00",
    type: "text",
  },
  {
    id: "m17",
    senderId: "u6",
    content: "Copy landing page udah final ya. Bisa mulai di-implement.",
    timestamp: "2026-06-25T14:00:00",
    type: "text",
  },
];

export const notes: Note[] = [
  {
    id: "n1",
    userId: "u1",
    title: "Meeting Notes",
    content:
      "- Sprint review minggu depan\n- Prioritaskan bug critical\n- Deploy v2.0 akhir bulan",
    createdAt: "2026-06-20",
    updatedAt: "2026-06-20",
    color: "#3b82f6",
  },
  {
    id: "n2",
    userId: "u1",
    title: "Ide Fitur Baru",
    content:
      "1. Dark mode\n2. Notifikasi push\n3. Export PDF\n4. Integrasikan Google Calendar",
    createdAt: "2026-06-22",
    updatedAt: "2026-06-22",
    color: "#8b5cf6",
  },
  {
    id: "n3",
    userId: "u3",
    title: "Belajar Next.js 16",
    content:
      "- App Router sudah stable\n- Server Components default\n- Suspense untuk streaming\n- Dynamic routes dengan [id]",
    createdAt: "2026-06-18",
    updatedAt: "2026-06-19",
    color: "#10b981",
  },
  {
    id: "n4",
    userId: "u5",
    content:
      "Deadline konten Instagram: 1 Juli\nMinimal 12 post\nTema: produktivitas",
    title: "Instagram Content Plan",
    createdAt: "2026-06-15",
    updatedAt: "2026-06-15",
    color: "#f59e0b",
  },
  {
    id: "n5",
    userId: "u1",
    title: "Rencana Q3 2026",
    content:
      "1. Launch mobile app\n2. Expand ke 3 kota baru\n3. Hiring 5 engineer\n4. Revenue target: 500 juta/bulan",
    createdAt: "2026-06-23",
    updatedAt: "2026-06-23",
    color: "#059669",
  },
  {
    id: "n6",
    userId: "u2",
    title: "Campaign Lebaran",
    content:
      "- Budget: 50 juta\n- Timeline: 1 Agustus - 15 Agustus\n- Channel: Instagram, TikTok, Email\n- KPI: 10k new users",
    createdAt: "2026-06-24",
    updatedAt: "2026-06-24",
    color: "#dc2626",
  },
  {
    id: "n7",
    userId: "u3",
    title: "Bug Tracker",
    content:
      "BUG-001: Login timeout di mobile\nBUG-002: Chat notification tidak muncul\nBUG-003: File upload limit 5MB\nBUG-004: Calendar sync error",
    createdAt: "2026-06-25",
    updatedAt: "2026-06-25",
    color: "#ea580c",
  },
  {
    id: "n8",
    userId: "u7",
    title: "Design System v2",
    content:
      "Color palette:\n- Primary: #F5A623\n- Success: #4CAF50\n- Error: #E53935\n- Neutral: #6B6B6B\n\nTypography: Inter, 14px base",
    createdAt: "2026-06-20",
    updatedAt: "2026-06-22",
    color: "#7c3aed",
  },
  {
    id: "n9",
    userId: "u4",
    title: "Server Monitoring",
    content:
      "Uptime target: 99.9%\nResponse time: < 200ms\nError rate: < 0.1%\n\nTools: Grafana + Prometheus\nAlert ke Slack #ops",
    createdAt: "2026-06-21",
    updatedAt: "2026-06-21",
    color: "#0891b2",
  },
  {
    id: "n10",
    userId: "u5",
    title: "Content Ideas",
    content:
      "1. Behind the scenes tim dev\n2. Tutorial singkat fitur baru\n3. Testimoni user\n4. Tips produktivitas\n5. Infografik statistik app",
    createdAt: "2026-06-22",
    updatedAt: "2026-06-23",
    color: "#d946ef",
  },
  {
    id: "n11",
    userId: "u6",
    title: "Email Templates",
    content:
      "1. Welcome email\n2. Weekly digest\n3. Feature announcement\n4. Re-engagement\n5. Feedback request\n\nCopy deadline: 5 Juli",
    createdAt: "2026-06-24",
    updatedAt: "2026-06-24",
    color: "#2563eb",
  },
  {
    id: "n12",
    userId: "u8",
    title: "Icon Library",
    content:
      "Icons yang dibutuhkan:\n- Navigation (12)\n- Actions (20)\n- Status (8)\n- Social (6)\n\nFormat: SVG, 24x24\nStroke: 2px",
    createdAt: "2026-06-23",
    updatedAt: "2026-06-23",
    color: "#be185d",
  },
];

export const calendarEvents: CalendarEvent[] = [
  {
    id: "e1",
    title: "Hari Raya Idul Adha",
    date: "2026-06-07",
    type: "holiday",
    description: "Libur nasional",
  },
  {
    id: "e2",
    title: "Hari Kemerdekaan RI",
    date: "2026-08-17",
    type: "holiday",
    description: "Libur nasional",
  },
  {
    id: "e3",
    title: "Deadline: Desain UI Dashboard v2",
    date: "2026-07-15",
    type: "deadline",
    taskId: "t1",
  },
  {
    id: "e4",
    title: "Deadline: API Authentication",
    date: "2026-07-10",
    type: "deadline",
    taskId: "t2",
  },
  {
    id: "e5",
    title: "Deadline: Konten Instagram",
    date: "2026-07-01",
    type: "deadline",
    taskId: "t3",
  },
  {
    id: "e6",
    title: "Sprint Review",
    date: "2026-06-30",
    type: "plan",
    userId: "u1",
    description: "Review sprint bulan ini",
  },
  {
    id: "e7",
    title: "Team Building",
    date: "2026-07-20",
    type: "plan",
    userId: "u1",
    description: "Outing team",
  },
  {
    id: "e8",
    title: "Deadline: Video Tutorial",
    date: "2026-06-25",
    type: "deadline",
    taskId: "t5",
  },
  {
    id: "e9",
    title: "Client Meeting - PT Maju",
    date: "2026-06-26",
    type: "meeting",
    description: "Presentasi progress project",
  },
  {
    id: "e10",
    title: "Deadline: Riset Kompetitor",
    date: "2026-07-08",
    type: "deadline",
    taskId: "t9",
  },
  {
    id: "e11",
    title: "Deadline: Payment Gateway",
    date: "2026-07-12",
    type: "deadline",
    taskId: "t10",
  },
  {
    id: "e12",
    title: "Weekly Standup",
    date: "2026-06-27",
    type: "plan",
    userId: "u1",
    description: "Standup mingguan tim",
  },
  {
    id: "e13",
    title: "Design Review",
    date: "2026-06-28",
    type: "meeting",
    description: "Review desain mobile app",
  },
  {
    id: "e14",
    title: "Deadline: Logo Redesign",
    date: "2026-07-03",
    type: "deadline",
    taskId: "t16",
  },
];

export const chatContacts: ChatContact[] = [
  {
    id: "c1",
    userId: "u2",
    lastMessage: "Meeting jam 3 sore ya.",
    lastMessageTime: "2026-06-25T08:00:00",
    unread: 2,
    online: true,
  },
  {
    id: "c2",
    userId: "u3",
    lastMessage: "Saya juga join.",
    lastMessageTime: "2026-06-25T08:15:00",
    unread: 0,
    online: true,
  },
  {
    id: "c3",
    userId: "u4",
    lastMessage: "Oke, saya fokus ke responsive.",
    lastMessageTime: "2026-06-20T09:30:00",
    unread: 0,
    online: false,
  },
  {
    id: "c4",
    userId: "u5",
    lastMessage: "Siap pak!",
    lastMessageTime: "2026-06-25T08:10:00",
    unread: 1,
    online: true,
  },
  {
    id: "c5",
    userId: "u6",
    lastMessage: "Konten sudah ready.",
    lastMessageTime: "2026-06-24T14:00:00",
    unread: 0,
    online: false,
  },
  {
    id: "c6",
    userId: "u7",
    lastMessage: "Color palette sudah jadi.",
    lastMessageTime: "2026-06-23T10:00:00",
    unread: 0,
    online: true,
  },
  {
    id: "c7",
    userId: "u8",
    lastMessage: "Banner versi final sudah dikirim.",
    lastMessageTime: "2026-06-22T16:00:00",
    unread: 0,
    online: false,
  },
];

export function getUserById(id: string): User | undefined {
  return users.find((u) => u.id === id);
}

export function getUsersByIds(ids: string[]): User[] {
  return ids
    .map((id) => users.find((u) => u.id === id))
    .filter(Boolean) as User[];
}

export function getTasksByAssignee(userId: string): Task[] {
  return tasks.filter((t) => t.assigneeIds.includes(userId));
}

export function getTasksByLeader(leaderId: string): Task[] {
  return tasks.filter((t) => t.leaderId === leaderId);
}

export function getMessagesByTask(taskId: string): Message[] {
  return messages.filter((m) => m.taskId === taskId);
}

export function getUniversalMessages(): Message[] {
  return messages.filter((m) => !m.taskId);
}
